# Generated by Django 5.1.2 on 2024-10-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_enquiery_user_alter_enquiery_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiery',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='enquiery',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
