# Generated by Django 5.1.2 on 2024-10-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_enquiery_description_alter_enquiery_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiery',
            name='phone',
            field=models.IntegerField(default=1),
        ),
    ]
