# Generated by Django 5.1.2 on 2024-10-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_enquiery_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiery',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='enquiery',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enquiery',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
