# Generated by Django 5.1.2 on 2024-10-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_enquiery_event_remove_enquiery_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiery',
            name='event',
            field=models.CharField(default='wed', max_length=200),
        ),
    ]
