# Generated by Django 5.1.2 on 2024-11-02 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_enquiery_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
