# Generated by Django 5.1.2 on 2024-11-03 07:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_bookevent_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiery',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
